version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  build-and-deploy:
    resource_class: small
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - aws-s3/sync:
          from: './src'
          to: 's3://tools.thecjgcjg.com/playlist-creator/'
          overwrite: true
      - run: aws cloudfront create-invalidation --distribution-id ED3R28U1ZOODQ --paths '/playlist-creator/*'
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy
